"""Add cascade on delete

Revision ID: 08719b97d34a
Revises: 8be75cfe2c5d
Create Date: 2026-04-12 19:36:42.406913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08719b97d34a'
down_revision = '8be75cfe2c5d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foto_requests', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('foto_requests_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'requests', ['id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('mail_requests', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('mail_requests_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'requests', ['id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mail_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('mail_requests_id_fkey'), 'requests', ['id'], ['id'])

    with op.batch_alter_table('foto_requests', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('foto_requests_id_fkey'), 'requests', ['id'], ['id'])

    # ### end Alembic commands ###
