"""Add columns to Foto requests

Revision ID: 8be75cfe2c5d
Revises: e97877277441
Create Date: 2026-04-12 19:29:30.911378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8be75cfe2c5d'
down_revision = 'e97877277441'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foto_requests', schema=None) as batch_op:
        batch_op.add_column(sa.Column('habitat', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('in_pericolo', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('foto_requests', schema=None) as batch_op:
        batch_op.drop_column('in_pericolo')
        batch_op.drop_column('habitat')

    # ### end Alembic commands ###
