"""initial migration

Revision ID: e97877277441
Revises: 
Create Date: 2026-04-12 13:49:18.242842

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e97877277441'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=50), nullable=False),
    sa.Column('hash_password', sa.String(length=255), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('modify_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('foto_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('foto_path', sa.Text(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=True),
    sa.Column('classe', sa.String(length=50), nullable=True),
    sa.Column('ordine', sa.String(length=50), nullable=True),
    sa.Column('famiglia', sa.String(length=50), nullable=True),
    sa.Column('genere', sa.String(length=50), nullable=True),
    sa.Column('specie', sa.String(length=50), nullable=True),
    sa.Column('pericolosita', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('mail_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mail_text', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=True),
    sa.Column('suggested_reply', sa.Text(), nullable=True),
    sa.Column('extracted_data', sa.Text(), nullable=True),
    sa.Column('feedback', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mail_requests')
    op.drop_table('foto_requests')
    op.drop_table('users')
    op.drop_table('requests')
    # ### end Alembic commands ###
